# setting up dev enviorment
FROM ubuntu:latest
RUN apt-get -y update
RUN apt-get -y install git
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt install python3.10
RUN apt-get -y install python3-pip
RUN apt-get -y install nodejs npm
WORKDIR /code/frontend
# copying project over 
# js front end
COPY frontend/package*.json /code/frontend
RUN npm install
COPY frontend/. /code/frontend
# python backend
RUN apt-get install -y python3-distutils
WORKDIR /code/backend
COPY backend/requirements.txt /code/backend
RUN pip install -r requirements.txt
COPY backend/. /code/backend
