# Generated by Django 3.2.16 on 2023-02-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('bldg', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
