# Generated by Django 3.2.16 on 2023-02-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_testingroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingroom',
            name='bldg',
            field=models.CharField(max_length=100),
        ),
    ]
