# Generated by Django 3.2.16 on 2023-02-14 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_testingroom_bldg'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingRoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('is_booked', models.BooleanField(default=False)),
                ('testing_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testingroom')),
            ],
        ),
    ]
