# Generated by Django 3.2.16 on 2023-02-19 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_testingroomavailability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testingroomavailability',
            unique_together={('testing_room', 'start_time', 'end_time', 'date')},
        ),
    ]
