# Generated by Django 3.2.16 on 2023-02-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_testingroomavailability_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testingroom',
            unique_together={('room_number', 'bldg')},
        ),
    ]
