# Generated by Django 3.2.16 on 2023-03-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_professorreservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfessorReservation',
        ),
    ]
