# Generated by Django 3.2.16 on 2023-03-19 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_professorreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorreservation',
            name='room_aval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testingroomavailability', unique=True),
        ),
    ]
