# Generated by Django 3.2.16 on 2023-02-02 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(choices=[('STUDENT', 'student'), ('ADMIN', 'admin'), ('PROCTOR', 'proctor'), ('PROFESSOR', 'professor')], default='STUDENT', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='professor',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='siteadmin',
            name='site_admin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student',
        ),
        migrations.DeleteModel(
            name='Proctor',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='SiteAdmin',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
