# Generated by Django 3.2.16 on 2023-02-02 00:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_user_usertype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Accounts',
        ),
    ]
